from app.models import db, Tag

def seed_tags():
  one = Tag(userId=49, imageId=1, name='ice')
  two = Tag(userId=49, imageId=1, name='snow')
  three = Tag(userId=49, imageId=1, name='mountain')
  four = Tag(userId=49, imageId=1, name='winter')
  five = Tag(userId=49, imageId=1, name='cold')

  six = Tag(userId=49, imageId=2, name='city')
  seven = Tag(userId=49, imageId=2, name='night')
  eight = Tag(userId=49, imageId=2, name='lights')
  nine = Tag(userId=49, imageId=2, name='sky')
  ten = Tag(userId=49, imageId=2, name='building')

  eleven = Tag(userId=49, imageId=3, name='ice')
  twelve = Tag(userId=49, imageId=3, name='snow')
  thirteen = Tag(userId=49, imageId=3, name='mountain')
  fourteen = Tag(userId=49, imageId=3, name='winter')
  fifteen = Tag(userId=49, imageId=3, name='cold')

  sixteen = Tag(userId=49, imageId=4, name='desert')
  seventeen = Tag(userId=49, imageId=4, name='sand')
  eighteen = Tag(userId=49, imageId=4, name='sun')
  nineteen = Tag(userId=49, imageId=4, name='hot')
  twenty = Tag(userId=49, imageId=4, name='dry')

  twentyone = Tag(userId=49, imageId=5, name='water')
  twentytwo = Tag(userId=49, imageId=5, name='lake')
  twentythree = Tag(userId=49, imageId=5, name='boat')
  twentyfour = Tag(userId=49, imageId=5, name='reflection')
  twentyfive = Tag(userId=49, imageId=5, name='sky')

  twentysix = Tag(userId=49, imageId=6, name='night')
  twentyseven = Tag(userId=49, imageId=6, name='city')
  twentyeight = Tag(userId=49, imageId=6, name='lights')
  twentynine = Tag(userId=49, imageId=6, name='building')
  thirty = Tag(userId=49, imageId=6, name='car')

  thirtyone = Tag(userId=49, imageId=7, name='neon')
  thirtytwo = Tag(userId=49, imageId=7, name='light')
  thirtythree = Tag(userId=49, imageId=7, name='city')
  thirtyfour = Tag(userId=49, imageId=7, name='night')
  thirtyfive = Tag(userId=49, imageId=7, name='building')

  thirtysix = Tag(userId=49, imageId=8, name='water')
  thirtyseven = Tag(userId=49, imageId=8, name='lake')
  thirtyeight = Tag(userId=49, imageId=8, name='mountain')
  thirtynine = Tag(userId=49, imageId=8, name='bridge')
  forty = Tag(userId=49, imageId=8, name='cloud')

  fortyone = Tag(userId=49, imageId=9, name='city')
  fortytwo = Tag(userId=49, imageId=9, name='sunset')
  fortythree = Tag(userId=49, imageId=9, name='building')
  fortyfour = Tag(userId=49, imageId=9, name='city')
  fortyfive = Tag(userId=49, imageId=9, name='sky')

  fortysix = Tag(userId=49, imageId=10, name='water')
  fortyseven = Tag(userId=49, imageId=10, name='lake')
  fortyeight = Tag(userId=49, imageId=10, name='mountain')
  fortynine = Tag(userId=49, imageId=10, name='reflection')
  fifty = Tag(userId=49, imageId=10, name='sky')

  fiftyone = Tag(userId=49, imageId=11, name='tree')
  fiftytwo = Tag(userId=49, imageId=11, name='hike')
  fiftythree = Tag(userId=49, imageId=11, name='cloud')
  fiftyfour = Tag(userId=49, imageId=11, name='mountain')
  fiftyfive = Tag(userId=49, imageId=11, name='person')

  fiftysix = Tag(userId=49, imageId=12, name='road')
  fiftyseven = Tag(userId=49, imageId=12, name='mountain')
  fiftyeight = Tag(userId=49, imageId=12, name='cloud')
  fiftynine = Tag(userId=49, imageId=12, name='tree')
  sixty = Tag(userId=49, imageId=12, name='empty')

  sixtyone = Tag(userId=49, imageId=13, name='tree')
  sixtytwo = Tag(userId=49, imageId=13, name='mountain')
  sixtythree = Tag(userId=49, imageId=13, name='free')
  sixtyfour = Tag(userId=49, imageId=13, name='grass')
  sixtyfive = Tag(userId=49, imageId=13, name='morning')

  sixtysix = Tag(userId=49, imageId=14, name='camera')
  sixtyseven = Tag(userId=49, imageId=14, name='photography')
  sixtyeight = Tag(userId=49, imageId=14, name='person')
  sixtynine = Tag(userId=49, imageId=14, name='captured')
  seventy = Tag(userId=49, imageId=14, name='lens')

  seventyone = Tag(userId=49, imageId=15, name='lake')
  seventytwo = Tag(userId=49, imageId=15, name='tree')
  seventythree = Tag(userId=49, imageId=15, name='mountain')
  seventyfour = Tag(userId=49, imageId=15, name='calm')
  seventyfive = Tag(userId=49, imageId=15, name='water')

  seventysix = Tag(userId=49, imageId=16, name='mountain')
  seventyseven = Tag(userId=49, imageId=16, name='house')
  seventyeight = Tag(userId=49, imageId=16, name='person')
  seventynine = Tag(userId=49, imageId=16, name='hill')
  eighty = Tag(userId=49, imageId=16, name='rock')

  eightyone = Tag(userId=49, imageId=17, name='cow')
  eightytwo = Tag(userId=49, imageId=17, name='moo')
  eightythree = Tag(userId=49, imageId=17, name='tree')
  eightyfour = Tag(userId=49, imageId=17, name='mountain')
  eightyfive = Tag(userId=49, imageId=17, name='grass')

  eightysix = Tag(userId=49, imageId=18, name='lake')
  eightyseven = Tag(userId=49, imageId=18, name='water')
  eightyeight = Tag(userId=49, imageId=18, name='mountain')
  eightynine = Tag(userId=49, imageId=18, name='tree')
  ninety = Tag(userId=49, imageId=18, name='clear')

  ninetyone = Tag(userId=49, imageId=19, name='green')
  ninetytwo = Tag(userId=49, imageId=19, name='grass')
  ninetythree = Tag(userId=49, imageId=19, name='tree')
  ninetyfour = Tag(userId=49, imageId=19, name='house')
  ninetyfive = Tag(userId=49, imageId=19, name='hill')

  ninetysix = Tag(userId=49, imageId=20, name='city')
  ninetyseven = Tag(userId=49, imageId=20, name='night')
  ninetyeight = Tag(userId=49, imageId=20, name='light')
  ninetynine = Tag(userId=49, imageId=20, name='people')
  onehundred = Tag(userId=49, imageId=20, name='building')

  onehundredone = Tag(userId=49, imageId=21, name='japan')
  onehundredtwo = Tag(userId=49, imageId=21, name='fuji')
  onehundredthree = Tag(userId=49, imageId=21, name='mountain')
  onehundredfour = Tag(userId=49, imageId=21, name='temple')
  onehundredfive = Tag(userId=49, imageId=21, name='sunset')

  onehundredsix = Tag(userId=49, imageId=22, name='bridge')
  onehundredseven = Tag(userId=49, imageId=22, name='water')
  onehundredeight = Tag(userId=49, imageId=22, name='boat')
  onehundrednine = Tag(userId=49, imageId=22, name='sunset')
  onehundredten = Tag(userId=49, imageId=22, name='london')

  onehundredeleven = Tag(userId=49, imageId=23, name='night')
  onehundredtwelve = Tag(userId=49, imageId=23, name='water')
  onehundredthirteen = Tag(userId=49, imageId=23, name='light')
  onehundredfourteen = Tag(userId=49, imageId=23, name='dark')
  onehundredfifteen = Tag(userId=49, imageId=23, name='boat')

  onehundredsixteen = Tag(userId=49, imageId=24, name='night')
  onehundredseventeen = Tag(userId=49, imageId=24, name='street')
  onehundredeighteen = Tag(userId=49, imageId=24, name='lights')
  onehundrednineteen = Tag(userId=49, imageId=24, name='city')
  onehundredtwenty = Tag(userId=49, imageId=24, name='building')

  onehundredtwentyone = Tag(userId=49, imageId=25, name='water')
  onehundredtwentytwo = Tag(userId=49, imageId=25, name='tree')
  onehundredtwentythree = Tag(userId=49, imageId=25, name='relax')
  onehundredtwentyfour = Tag(userId=49, imageId=25, name='chill')
  onehundredtwentyfive = Tag(userId=49, imageId=25, name='clouds')

  onehundredtwentysix = Tag(userId=49, imageId=26, name='night')
  onehundredtwentyseven = Tag(userId=49, imageId=26, name='city')
  onehundredtwentyeight = Tag(userId=49, imageId=26, name='building')
  onehundredtwentynine = Tag(userId=49, imageId=26, name='dark')
  onehundredthirty = Tag(userId=49, imageId=26, name='traffic')

  onehundredthirtyone = Tag(userId=49, imageId=27, name='boat')
  onehundredthirtytwo = Tag(userId=49, imageId=27, name='water')
  onehundredthirtythree = Tag(userId=49, imageId=27, name='mountain')
  onehundredthirtyfour = Tag(userId=49, imageId=27, name='island')
  onehundredthirtyfive = Tag(userId=49, imageId=27, name='clear')

  onehundredthirtysix = Tag(userId=49, imageId=28, name='bigben')
  onehundredthirtyseven = Tag(userId=49, imageId=28, name='london')
  onehundredthirtyeight = Tag(userId=49, imageId=28, name='clock')
  onehundredthirtynine = Tag(userId=49, imageId=28, name='tower')
  onehundredforty = Tag(userId=49, imageId=28, name='cloudy')

  onehundredfortyone = Tag(userId=49, imageId=29, name='reflection')
  onehundredfortytwo = Tag(userId=49, imageId=29, name='city')
  onehundredfortythree = Tag(userId=49, imageId=29, name='building')
  onehundredfortyfour = Tag(userId=49, imageId=29, name='lights')
  onehundredfortyfive = Tag(userId=49, imageId=29, name='night')

  onehundredfortysix = Tag(userId=49, imageId=30, name='water')
  onehundredfortyseven = Tag(userId=49, imageId=30, name='boat')
  onehundredfortyeight = Tag(userId=49, imageId=30, name='lake')
  onehundredfortynine = Tag(userId=49, imageId=30, name='trees')
  onehundredfifty = Tag(userId=49, imageId=30, name='alone')

  onehundredfiftyone = Tag(userId=49, imageId=31, name='car')
  onehundredfiftytwo = Tag(userId=49, imageId=31, name='mountain')
  onehundredfiftythree = Tag(userId=49, imageId=31, name='cloudy')
  onehundredfiftyfour = Tag(userId=49, imageId=31, name='dirt')
  onehundredfiftyfive = Tag(userId=49, imageId=31, name='white')

  onehundredfiftysix = Tag(userId=49, imageId=32, name='city')
  onehundredfiftyseven = Tag(userId=49, imageId=32, name='building')
  onehundredfiftyeight = Tag(userId=49, imageId=32, name='lights')
  onehundredfiftynine = Tag(userId=49, imageId=32, name='night')
  onehundredsixty = Tag(userId=49, imageId=32, name='dark')

  onehundredsixtyone = Tag(userId=49, imageId=33, name='desert')
  onehundredsixtytwo = Tag(userId=49, imageId=33, name='sand')
  onehundredsixtythree = Tag(userId=49, imageId=33, name='mountain')
  onehundredsixtyfour = Tag(userId=49, imageId=33, name='dry')
  onehundredsixtyfive = Tag(userId=49, imageId=33, name='hot')

  onehundredsixtysix = Tag(userId=49, imageId=34, name='night')
  onehundredsixtyseven = Tag(userId=49, imageId=34, name='lantern')
  onehundredsixtyeight = Tag(userId=49, imageId=34, name='lights')
  onehundredsixtynine = Tag(userId=49, imageId=34, name='street')
  onehundredseventy = Tag(userId=49, imageId=34, name='city')

  onehundredseventyone = Tag(userId=49, imageId=35, name='northern')
  onehundredseventytwo = Tag(userId=49, imageId=35, name='lights')
  onehundredseventythree = Tag(userId=49, imageId=35, name='aurora')
  onehundredseventyfour = Tag(userId=49, imageId=35, name='sky')
  onehundredseventyfive = Tag(userId=49, imageId=35, name='night')

  onehundredseventysix = Tag(userId=49, imageId=36, name='village')
  onehundredseventyseven = Tag(userId=49, imageId=36, name='mountain')
  onehundredseventyeight = Tag(userId=49, imageId=36, name='tree')
  onehundredseventynine = Tag(userId=49, imageId=36, name='clouds')
  onehundredeighty = Tag(userId=49, imageId=36, name='sky')

  onehundredeightyone = Tag(userId=49, imageId=37, name='building')
  onehundredeightytwo = Tag(userId=49, imageId=37, name='city')
  onehundredeightythree = Tag(userId=49, imageId=37, name='lights')
  onehundredeightyfour = Tag(userId=49, imageId=37, name='night')
  onehundredeightyfive = Tag(userId=49, imageId=37, name='dark')

  onehundredeightysix = Tag(userId=49, imageId=38, name='boats')
  onehundredeightyseven = Tag(userId=49, imageId=38, name='water')
  onehundredeightyeight = Tag(userId=49, imageId=38, name='harbor')
  onehundredeightynine = Tag(userId=49, imageId=38, name='dock')


  onehundredninety = Tag(userId=49, imageId=39, name='tree')
  onehundredninetyone = Tag(userId=49, imageId=39, name='mountain')
  onehundredninetytwo = Tag(userId=49, imageId=39, name='clouds')
  onehundredninetythree = Tag(userId=49, imageId=39, name='volcano')
  onehundredninetyfour = Tag(userId=49, imageId=39, name='sky')

  onehundredninetyfive = Tag(userId=49, imageId=40, name='nyc')
  onehundredninetysix = Tag(userId=49, imageId=40, name='city')
  onehundredninetyseven = Tag(userId=49, imageId=40, name='traffic')
  onehundredninetyeight = Tag(userId=49, imageId=40, name='cars')
  onehundredninetynine = Tag(userId=49, imageId=40, name='cloudy')

  twohundred = Tag(userId=49, imageId=41, name='river')
  twohundredone = Tag(userId=49, imageId=41, name='water')
  twohundredtwo = Tag(userId=49, imageId=41, name='clouds')
  twohundredthree = Tag(userId=49, imageId=41, name='tree')
  twohundredfour = Tag(userId=49, imageId=41, name='clock')

  twohundredfive = Tag(userId=49, imageId=42, name='water')
  twohundredsix = Tag(userId=49, imageId=42, name='tree')
  twohundredseven = Tag(userId=49, imageId=42, name='blue')
  twohundredeight = Tag(userId=49, imageId=42, name='sand')
  twohundrednine = Tag(userId=49, imageId=42, name='beach')

  twohundredten = Tag(userId=49, imageId=43, name='reflection')
  twohundredeleven = Tag(userId=49, imageId=43, name='city')
  twohundredtwelve = Tag(userId=49, imageId=43, name='lights')
  twohundredthirteen = Tag(userId=49, imageId=43, name='building')
  twohundredfourteen = Tag(userId=49, imageId=43, name='purple')

  twohundredfifteen = Tag(userId=49, imageId=44, name='water')
  twohundredsixteen = Tag(userId=49, imageId=44, name='reflection')
  twohundredseventeen = Tag(userId=49, imageId=44, name='mountain')
  twohundredeighteen = Tag(userId=49, imageId=44, name='calm')
  twohundrednineteen = Tag(userId=49, imageId=44, name='lake')

  twohundredtwenty = Tag(userId=49, imageId=45, name='dry')
  twohundredtwentyone = Tag(userId=49, imageId=45, name='hike')
  twohundredtwentytwo = Tag(userId=49, imageId=45, name='mountain')
  twohundredtwentythree = Tag(userId=49, imageId=45, name='alone')
  twohundredtwentyfour = Tag(userId=49, imageId=45, name='solo')

  twohundredtwentyfive = Tag(userId=49, imageId=46, name='water')
  twohundredtwentysix = Tag(userId=49, imageId=46, name='tree')
  twohundredtwentyseven = Tag(userId=49, imageId=46, name='relax')
  twohundredtwentyeight = Tag(userId=49, imageId=46, name='beach')
  twohundredtwentynine = Tag(userId=49, imageId=46, name='sand')

  twohundredthirty = Tag(userId=49, imageId=47, name='water')
  twohundredthirtyone = Tag(userId=49, imageId=47, name='sunset')
  twohundredthirtytwo = Tag(userId=49, imageId=47, name='bridge')
  twohundredthirtythree = Tag(userId=49, imageId=47, name='cloudy')
  twohundredthirtyfour = Tag(userId=49, imageId=47, name='sky')

  twohundredthirtyfive = Tag(userId=49, imageId=48, name='road')
  twohundredthirtysix = Tag(userId=49, imageId=48, name='empty')
  twohundredthirtyseven = Tag(userId=49, imageId=48, name='mountain')
  twohundredthirtyeight = Tag(userId=49, imageId=48, name='rocky')
  twohundredthirtynine = Tag(userId=49, imageId=48, name='dry')

  twohundredforty = Tag(userId=49, imageId=49, name='chill')
  twohundredfortyone = Tag(userId=49, imageId=49, name='water')
  twohundredfortytwo = Tag(userId=49, imageId=49, name='lake')
  twohundredfortythree = Tag(userId=49, imageId=49, name='relax')
  twohundredfortyfour = Tag(userId=49, imageId=49, name='shoes')

  twohundredfortyfive = Tag(userId=49, imageId=50, name='leaves')
  twohundredfortysix = Tag(userId=49, imageId=50, name='sun')
  twohundredfortyseven = Tag(userId=49, imageId=50, name='autumn')
  twohundredfortyeight = Tag(userId=49, imageId=50, name='fall')
  twohundredfortynine = Tag(userId=49, imageId=50, name='tree')

  db.session.add(one)
  db.session.add(two)
  db.session.add(three)
  db.session.add(four)
  db.session.add(five)
  db.session.add(six)
  db.session.add(seven)
  db.session.add(eight)
  db.session.add(nine)
  db.session.add(ten)
  db.session.add(eleven)
  db.session.add(twelve)
  db.session.add(thirteen)
  db.session.add(fourteen)
  db.session.add(fifteen)
  db.session.add(sixteen)
  db.session.add(seventeen)
  db.session.add(eighteen)
  db.session.add(nineteen)
  db.session.add(twenty)
  db.session.add(twentyone)
  db.session.add(twentytwo)
  db.session.add(twentythree)
  db.session.add(twentyfour)
  db.session.add(twentyfive)
  db.session.add(twentysix)
  db.session.add(twentyseven)
  db.session.add(twentyeight)
  db.session.add(twentynine)
  db.session.add(thirty)
  db.session.add(thirtyone)
  db.session.add(thirtytwo)
  db.session.add(thirtythree)
  db.session.add(thirtyfour)
  db.session.add(thirtyfive)
  db.session.add(thirtysix)
  db.session.add(thirtyseven)
  db.session.add(thirtyeight)
  db.session.add(thirtynine)
  db.session.add(forty)
  db.session.add(fortyone)
  db.session.add(fortytwo)
  db.session.add(fortythree)
  db.session.add(fortyfour)
  db.session.add(fortyfive)
  db.session.add(fortysix)
  db.session.add(fortyseven)
  db.session.add(fortyeight)
  db.session.add(fortynine)
  db.session.add(fifty)
  db.session.add(fiftyone)
  db.session.add(fiftytwo)
  db.session.add(fiftythree)
  db.session.add(fiftyfour)
  db.session.add(fiftyfive)
  db.session.add(fiftysix)
  db.session.add(fiftyseven)
  db.session.add(fiftyeight)
  db.session.add(fiftynine)
  db.session.add(sixty)
  db.session.add(sixtyone)
  db.session.add(sixtytwo)
  db.session.add(sixtythree)
  db.session.add(sixtyfour)
  db.session.add(sixtyfive)
  db.session.add(sixtysix)
  db.session.add(sixtyseven)
  db.session.add(sixtyeight)
  db.session.add(sixtynine)
  db.session.add(seventy)
  db.session.add(seventyone)
  db.session.add(seventytwo)
  db.session.add(seventythree)
  db.session.add(seventyfour)
  db.session.add(seventyfive)
  db.session.add(seventysix)
  db.session.add(seventyseven)
  db.session.add(seventyeight)
  db.session.add(seventynine)
  db.session.add(eighty)
  db.session.add(eightyone)
  db.session.add(eightytwo)
  db.session.add(eightythree)
  db.session.add(eightyfour)
  db.session.add(eightyfive)
  db.session.add(eightysix)
  db.session.add(eightyseven)
  db.session.add(eightyeight)
  db.session.add(eightynine)
  db.session.add(ninety)
  db.session.add(ninetyone)
  db.session.add(ninetytwo)
  db.session.add(ninetythree)
  db.session.add(ninetyfour)
  db.session.add(ninetyfive)
  db.session.add(ninetysix)
  db.session.add(ninetyseven)
  db.session.add(ninetyeight)
  db.session.add(ninetynine)
  db.session.add(onehundred)
  db.session.add(onehundredone)
  db.session.add(onehundredtwo)
  db.session.add(onehundredthree)
  db.session.add(onehundredfour)
  db.session.add(onehundredfive)
  db.session.add(onehundredsix)
  db.session.add(onehundredseven)
  db.session.add(onehundredeight)
  db.session.add(onehundrednine)
  db.session.add(onehundredten)
  db.session.add(onehundredeleven)
  db.session.add(onehundredtwelve)
  db.session.add(onehundredthirteen)
  db.session.add(onehundredfourteen)
  db.session.add(onehundredfifteen)
  db.session.add(onehundredsixteen)
  db.session.add(onehundredseventeen)
  db.session.add(onehundredeighteen)
  db.session.add(onehundrednineteen)
  db.session.add(onehundredtwenty)
  db.session.add(onehundredtwentyone)
  db.session.add(onehundredtwentytwo)
  db.session.add(onehundredtwentythree)
  db.session.add(onehundredtwentyfour)
  db.session.add(onehundredtwentyfive)
  db.session.add(onehundredtwentysix)
  db.session.add(onehundredtwentyseven)
  db.session.add(onehundredtwentyeight)
  db.session.add(onehundredtwentynine)
  db.session.add(onehundredthirty)
  db.session.add(onehundredthirtyone)
  db.session.add(onehundredthirtytwo)
  db.session.add(onehundredthirtythree)
  db.session.add(onehundredthirtyfour)
  db.session.add(onehundredthirtyfive)
  db.session.add(onehundredthirtysix)
  db.session.add(onehundredthirtyseven)
  db.session.add(onehundredthirtyeight)
  db.session.add(onehundredthirtynine)
  db.session.add(onehundredforty)
  db.session.add(onehundredfortyone)
  db.session.add(onehundredfortytwo)
  db.session.add(onehundredfortythree)
  db.session.add(onehundredfortyfour)
  db.session.add(onehundredfortyfive)
  db.session.add(onehundredfortysix)
  db.session.add(onehundredfortyseven)
  db.session.add(onehundredfortyeight)
  db.session.add(onehundredfortynine)
  db.session.add(onehundredfifty)
  db.session.add(onehundredfiftyone)
  db.session.add(onehundredfiftytwo)
  db.session.add(onehundredfiftythree)
  db.session.add(onehundredfiftyfour)
  db.session.add(onehundredfiftyfive)
  db.session.add(onehundredsixty)
  db.session.add(onehundredsixtyone)
  db.session.add(onehundredsixtytwo)
  db.session.add(onehundredsixtythree)
  db.session.add(onehundredsixtyfour)
  db.session.add(onehundredsixtyfive)
  db.session.add(onehundredsixtysix)
  db.session.add(onehundredsixtyseven)
  db.session.add(onehundredsixtyeight)
  db.session.add(onehundredsixtynine)
  db.session.add(onehundredseventy)
  db.session.add(onehundredseventyone)
  db.session.add(onehundredseventytwo)
  db.session.add(onehundredseventythree)
  db.session.add(onehundredseventyfour)
  db.session.add(onehundredseventyfive)
  db.session.add(onehundredseventysix)
  db.session.add(onehundredseventyseven)
  db.session.add(onehundredseventyeight)
  db.session.add(onehundredseventynine)
  db.session.add(onehundredeighty)
  db.session.add(onehundredeightyone)
  db.session.add(onehundredeightytwo)
  db.session.add(onehundredeightythree)
  db.session.add(onehundredeightyfour)
  db.session.add(onehundredeightyfive)
  db.session.add(onehundredeightysix)
  db.session.add(onehundredeightyseven)
  db.session.add(onehundredeightyeight)
  db.session.add(onehundredeightynine)
  db.session.add(onehundredninety)
  db.session.add(onehundredninetyone)
  db.session.add(onehundredninetytwo)
  db.session.add(onehundredninetythree)
  db.session.add(onehundredninetyfour)
  db.session.add(onehundredninetyfive)
  db.session.add(onehundredsixty)
  db.session.add(onehundredsixtyone)
  db.session.add(onehundredsixtytwo)
  db.session.add(onehundredsixtythree)
  db.session.add(onehundredsixtyfour)
  db.session.add(onehundredsixtyfive)
  db.session.add(onehundredsixtysix)
  db.session.add(onehundredsixtyseven)
  db.session.add(onehundredsixtyeight)
  db.session.add(onehundredsixtynine)
  db.session.add(onehundredseventy)
  db.session.add(onehundredseventyone)
  db.session.add(onehundredseventytwo)
  db.session.add(onehundredseventythree)
  db.session.add(onehundredseventyfour)
  db.session.add(onehundredseventyfive)
  db.session.add(onehundredseventysix)
  db.session.add(onehundredseventyseven)
  db.session.add(onehundredseventyeight)
  db.session.add(onehundredseventynine)
  db.session.add(onehundredeighty)
  db.session.add(onehundredeightyone)
  db.session.add(onehundredeightytwo)
  db.session.add(onehundredeightythree)
  db.session.add(onehundredeightyfour)
  db.session.add(onehundredeightyfive)
  db.session.add(onehundredeightysix)
  db.session.add(onehundredeightyseven)
  db.session.add(onehundredeightyeight)
  db.session.add(onehundredeightynine)
  db.session.add(onehundredninety)
  db.session.add(onehundredninetyone)
  db.session.add(onehundredninetytwo)
  db.session.add(onehundredninetythree)
  db.session.add(onehundredninetyfour)
  db.session.add(onehundredninetyfive)
  db.session.add(onehundredninetysix)
  db.session.add(onehundredninetyseven)
  db.session.add(onehundredninetyeight)
  db.session.add(onehundredninetynine)
  db.session.add(twohundred)
  db.session.add(twohundredone)
  db.session.add(twohundredtwo)
  db.session.add(twohundredthree)
  db.session.add(twohundredfour)
  db.session.add(twohundredfive)
  db.session.add(twohundredsix)
  db.session.add(twohundredseven)
  db.session.add(twohundredeight)
  db.session.add(twohundrednine)
  db.session.add(twohundredten)
  db.session.add(twohundredeleven)
  db.session.add(twohundredtwelve)
  db.session.add(twohundredthirteen)
  db.session.add(twohundredfourteen)
  db.session.add(twohundredfifteen)
  db.session.add(twohundredsixteen)
  db.session.add(twohundredseventeen)
  db.session.add(twohundredeighteen)
  db.session.add(twohundrednineteen)
  db.session.add(twohundredtwenty)
  db.session.add(twohundredtwentyone)
  db.session.add(twohundredtwentytwo)
  db.session.add(twohundredtwentythree)
  db.session.add(twohundredtwentyfour)
  db.session.add(twohundredtwentyfive)
  db.session.add(twohundredtwentysix)
  db.session.add(twohundredtwentyseven)
  db.session.add(twohundredtwentyeight)
  db.session.add(twohundredtwentynine)
  db.session.add(twohundredthirty)
  db.session.add(twohundredthirtyone)
  db.session.add(twohundredthirtytwo)
  db.session.add(twohundredthirtythree)
  db.session.add(twohundredthirtyfour)
  db.session.add(twohundredthirtyfive)
  db.session.add(twohundredthirtysix)
  db.session.add(twohundredthirtyseven)
  db.session.add(twohundredthirtyeight)
  db.session.add(twohundredthirtynine)
  db.session.add(twohundredforty)
  db.session.add(twohundredfortyone)
  db.session.add(twohundredfortytwo)
  db.session.add(twohundredfortythree)
  db.session.add(twohundredfortyfour)
  db.session.add(twohundredfortyfive)
  db.session.add(twohundredfortysix)
  db.session.add(twohundredfortyseven)
  db.session.add(twohundredfortyeight)
  db.session.add(twohundredfortynine)

  db.session.commit()


def undo_tags():
  db.session.execute('TRUNCATE likes RESTART IDENTITY CASCADE;')
  db.session.commit()
